### ISSUE TITLE
tanım yanlış

### ISSUE THREAD

**Issue by mdogancay** [php/doc-tr#12]
From manual page: https://php.net/function.preg-replace
This:
preg_replace(
    string|array $şablon,
    string|array $yenisi,
    string|array $yenisi,
    int $sınır = -1,
    int &$sayı = null
): string|array|null

will be:
preg_replace(
    string|array $şablon,
    string|array $yenisi,
    string|array $metin,
    int $sınır = -1,
    int &$adet = null
): string|array|null

Thanks.
---

**Comment by nilgun** [comment]
"adet" birimdir. 3 adet, 4 adet gibi. "miktar" olabilirdi. Ama "sayı" da yanlış değil.

**Comment by mdogancay** [comment]
> "adet" birimdir. 3 adet, 4 adet gibi. "miktar" olabilirdi. Ama "sayı" da yanlış değil.

Adet daha anlaşılır oluyor. Ama subject in yerine kullanılmış ki yanlış olmuş. Metin demek yada dizge demek daka mantıklı ve anlaşılır olur. Teşekkürler.
Selamlar.

**Comment by nilgun** [comment]
Murat Doğançay ***@***.***>, 4 Mar 2022 Cum, 20:37 tarihinde
şunu yazdı:

> "adet" birimdir. 3 adet, 4 adet gibi. "miktar" olabilirdi. Ama "sayı" da
> yanlış değil.
>
> Adet daha anlaşılır oluyor. Ama subject in yerine kullanılmış ki yanlış
> olmuş. Metin demek yada dizge demek daka mantıklı ve anlaşılır olur.
> Teşekkürler.
> Selamlar.
>
Ben yukarıyı farketmemişim. İki tane yenisi var... Düzeltiyorum.
