### ISSUE TITLE
Teşekkürlerrrr!

### ISSUE THREAD

**Issue by cem-canpolat** [php/doc-tr#19]
Merhaba,
Git, yazılım vs bu dünyada yeniyim, bunu buradan yazmam doğrumu bilmiyorum ama siz(ler)e çok çok teşekkür etmek istedim. Çevirileriniz çok önemli kıymetli hayat kurtarıyor diyebilirim. Değerli zamanınızı böyle bir işe ayırıp bizlerin anlamasına öğrenmesine yardımıcı olduğunuz için çok çok teşekkür ederim.

**Comment by nilgun** [comment]
24.08.2022 02:15 tarihinde Cem Canpolat yazdı:
> Merhaba,
> Git, yazılım vs bu dünyada yeniyim, bunu buradan yazmam doğrumu 
> bilmiyorum ama siz(ler)e çok çok teşekkür etmek istedim. Çevirileriniz 
> çok önemli kıymetli hayat kurtarıyor diyebilirim. Değerli zamanınızı 
> böyle bir işe ayırıp bizlerin anlamasına öğrenmesine yardımıcı olduğunuz 
> için çok çok teşekkür ederim.
> 
Merhaba, ben de teşekkür ederim, bu moral verici iletiniz için.

Elbette buradan da yazabilirsiniz ama konuyu kapatmayı unutmayın.
