### ISSUE TITLE
Berbat bir çeviri! gerçekten ülkeyi temsil etmiyor!

### ISSUE THREAD

**Issue by mdogancay** [php/doc-tr#7]
Arkadaşlar "Exception raising" olayını "YAVRULAMAK" diye çeviren hangi arkadaşımız ise kendisine söyleyin; o olaylar kendisine ÇOOOK YANLIŞ ANLATILMIŞ. (ne bileyim; "çıktılamak", "hata vermek" gibi tonla güzel benzetim varken "YAVRULAMAK"???)

Açıkçası sitenin Türkçe 'ye çevirimi BERBAT ÖTESİ!

Yakışmıyor! Bilginize!

**Comment by nilgun** [comment]
Hay hay buyrun çevirin, nereleydeydiniz? 12 senedir?
O bir istisna. O yavrulanır. Uzun süredir hata çıktılanmıyor.
O eskidendi. Herşey sınıflarla nesnelerle, istisnalarla yönetiliyor.
Siz PHP 4'te kalmışsınız.



Murat Doğançay ***@***.***>, 12 Tem 2021 Pzt, 14:25 tarihinde
şunu yazdı:

**Comment by mdogancay** [comment]
???
Birde küfür etseydiniz ? Belki daha iyi tatmin ederdi ?
Benim Türkçe çeviriye ihtiyacım yok. 30 yıldır bu meslekteyim. Ama gençler meraklı ve çoğu İngilizce bilmiyor.
Böyle bir çeviri ile bu işi öğrenmeleri çok zor. Saçma sapan kızgınlıklar yerine bu soruna nasıl çözüm buluruz tartışmak lazım.
Gerekirse geriye dönük çeviriler kontrol edilmeli. Hatta devlet desteği (İlgili üniversite ve liselerden) talep edilebilir.
Lise ve Üniversitelerimiz artık daha ilgili daha ETKİLİ.

Bir kerede insanlara hakaretvari cevaplar yazacağımıza SORUNUN ÇÖZÜMÜNE ODAKLANSAK? Ahh. Ahh..

**Comment by nilgun** [comment]
Bir istisnanın kullanıcıya ne yanıt vereceğini programcının kendisi
belirliyor artık (ini üzerinden).
Ben çeviriyi yaparken PHP'nin ne çıktılayacağını artık bilemiyorum. İstisna
yavrulanır diye çevirmekten başka şansım yok. Programcı ini dosyası
üzerinden hata mı, uyarı mı, bilgilendirme mi çıktılamak isteyeceğini veya
hiçbir çıktı verilmemesini mi tercih ettiğini ben bilemem.

Bunları siz bilmiyorsanız, ki öyle anlaşılıyor, haksız bir çıkarımda
bulunduğunuzu anlıyorum.
Belgeleri iyi okumamışsınız veya yanlış yorumlamışsınız. Büyük harflerle
(bağıra çağıra) yalanı ilan etmek elbette beni sinirlendiriyor.


Murat Doğançay ***@***.***>, 16 Tem 2021 Cum, 17:21 tarihinde
şunu yazdı:

**Comment by nilgun** [comment]
Çevirecek birilerini bulup github üzerinden PR ile çeviri ve düzeltme göndermeyi öğretirseniz oldukça faydalı olur. 12 yıldan fazladır Türkçe desteğini canlı tutmaya uğraşıyorum. Pek de güzel teşekkür ediyorsunuz. 30 + 3 yıl benimki...

**Comment by nilgun** [comment]
Bir ara belgeler.org'u da ziyaret edin. Oradaki çevirilerim için de fikirlerinizi alalım. C kılavuzu örneğin...
